name: build_MacOS_deploy

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
